spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/repacc
    username: postgres
    password: 1508
  flyway:
    enabled: true
    baseline-on-migrate: true
    cleanDisabled: false
zk:
  update-uri: /zkau
  loader-class: org.zkoss.zk.ui.http.DHtmlLayoutServlet
